### ISSUE TITLE
java.lang.IllegalArgumentException: Error occurred while converting unicode sequence String to String

### ISSUE THREAD

**Issue by greister** [michaelgantman/Mgnt#1]
The string want to convert :
`
 String = "\u767e\u5ea6\u767e\u79d1_\u5168\u7403\u6700\u5927\u4e2d\u6587\u767e\u79d1\u5168\u4e66"
`
`
java.lang.IllegalArgumentException: Error occurred while converting unicode sequence String to String
  com.mgnt.utils.StringUnicodeEncoderDecoder.decodeUnicodeSequenceToString(StringUnicodeEncoderDecoder.java:60)
  ammonite.$sess.cmd4$.<init>(cmd4.sc:1)
  ammonite.$sess.cmd4$.<clinit>(cmd4.sc)
java.lang.NumberFormatException: For input string: "百科_全球最大中文百科全书" under radix 16
  java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
  java.lang.Integer.parseInt(Integer.java:658)
  com.mgnt.utils.StringUnicodeEncoderDecoder.decodeUnicodeSequenceToString(StringUnicodeEncoderDecoder.java:57)
  ammonite.$sess.cmd4$.<init>(cmd4.sc:1)
  ammonite.$sess.cmd4$.<clinit>(cmd4.sc)`
`
run under  ammonite REPL

**Comment by michaelgantman** [comment]
Hello,
Even that I see that the issue was already closed, just to make sure - the problem is that in the input string there is an invalid code '\u79d1_' which was the cause of the error. In any case please feel free to contact me through opening an issue or directly if you need any assistance with this library.

**Comment by michaelgantman** [comment]
When I ran a test with your string I got the following stacktrace that points clearly at the problematic symbol in the string
Exception in thread "main" java.lang.IllegalArgumentException: Error occurred while converting unicode sequence String to String
	at com.mgnt.utils.StringUnicodeEncoderDecoder.decodeUnicodeSequenceToString(StringUnicodeEncoderDecoder.java:60)
	at com.test.StamTest.testEncoding(StamTest.java:121)
	at com.test.StamTest.main(StamTest.java:42)
Caused by: java.lang.NumberFormatException: For input string: "79d1_"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.mgnt.utils.StringUnicodeEncoderDecoder.decodeUnicodeSequenceToString(StringUnicodeEncoderDecoder.java:57)
	... 2 more

**Comment by michaelgantman** [comment]
When the problematic symbol was fixed (underscore removed) the conversion worked and the result was: 

> 百度百科全球最大中文百科全书

**Comment by michaelgantman** [comment]
Running the following code

> 		System.out.println(StringUnicodeEncoderDecoder.encodeStringToUnicodeSequence("百科_全球最大中文百科全书"));

Gave me the following output:

> \u767e\u79d1\u005f\u5168\u7403\u6700\u5927\u4e2d\u6587\u767e\u79d1\u5168\u4e66


Note the 3d symbol \u005f which is code for underscore ("_")
